### ISSUE TITLE
Idea: extend the API to allow finding out if a cell is already inited or not

### ISSUE THREAD

**Issue by dumblob** [tomhea/O1Array#13]
This could allow some interesting use cases which need something like `null-or-value` semantics before first write.

**Comment by tomhea** [comment]
That's a good issue, but I'm afraid it's a bit more complicated.

The is_inited() functionality works in blocks of size B (~128bits on a 64bit PC). When I access A[i], The algorithm also initialize some of the nearby array entries too, i.e. A[i-1], A[i+1], ... 
Also, the top block (actually, a bit smaller than that) might be already initialized from the start.

It is known in runtime which cells were initialized, but they might have been initialized by the algorithm itself, and not by the user that uses that array.
