### ISSUE TITLE
Get rid of exceptions (or make them optional)

### ISSUE THREAD

**Issue by dumblob** [tomhea/O1Array#14]
Many core systems nowadays expect single-header libs or generally low-level libs to not be dependent on C++ exceptions.

So to make this lib more appealing I propose to make it exception-less by default (or at least optionally exception-less).

**Comment by tomhea** [comment]
That's good advice!

I got into the project after about two years, and even fixed one of my tests :)

Now this lib is exception-less

I changed indexing to be circular, so A[i] is actually A[i % A.n]. It saves the need to use any exceptions.
If I didn't do it, I would still need to return something for the A[i>=A.n] reads/writes... A[i % A.n] might be the best option.
What do you think?

I'll document it of course.
